server:
  port: 8000
  servlet:
    # versioning is recommended i.e. /api/v1
    context-path: /api

spring:
  application:
    name: api

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true

  datasource:
    url: jdbc:h2:mem:testdb
    username: username
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace
